server:
  port: 9001

spring:
  application:
    name: user-service # microService name

eureka:
  client:
    # true: EUREKA? ??? ???.
    register-with-eureka: true
    # true: EUREKA ????? ?????? ??? ????? ??? ???? ???? ??
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # eureka ????? ??
