spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}\Desktop\study\springProject\MSA\MSA\git-local-repo

server:
  port: 8888
